import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
//Side Bar Imports
import SideNav from '@/components/ui/sidebar/side-nav';
import PageWrapper from '@/components/ui/page-wrapper';

export const metadata: Metadata = {
    title: 'Project Flow | Sign In',
    description: 'Generated by Project Flow Team Managers',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (

        <div className='relative flex h-screen w-full overflow-hidden'>
            <SideNav/>
            <PageWrapper>
                {children}
            </PageWrapper>
        </div>

    )
}
