import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import './globals.css'
import {Toaster} from "@/components/ui/toaster";
import AuthProvider from "@/context/AuthProvider";

//Side Bar Imports
import SideNav from '@/components/ui/sidebar/side-nav';
import PageWrapper from '@/components/ui/page-wrapper';
import MarginWidthWrapper from '@/components/ui/margin-width-wrapper';

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
    title: 'Project Flow | Sign In',
    description: 'Generated by Project Flow Team Managers',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
        <body className={`bg.white ${inter.className}`}>
        <AuthProvider>
            <div className='relative flex h-screen w-full overflow-hidden'>
                <SideNav/>
                <PageWrapper>
                    {children}
                </PageWrapper>
            </div>
        </AuthProvider>
        <Toaster/>
        </body>
        </html>
    )
}
