import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import {Toaster} from "@/components/ui/toaster";
import AuthProvider from "@/context/AuthProvider";

//Side Bar Imports 
import Header from '@/components/ui/header';
import HeaderMobile from '@/components/ui/header-mobile';
import SideNav from '@/components/ui/side-nav';
import PageWrapper from '@/components/ui/page-wrapper';
import MarginWidthWrapper from '@/components/ui/margin-width-wrapper';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Project Flow | Sign In',
  description: 'Generated by Project Flow Team Managers',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
        <body className={`bg.white ${inter.className}`}>
        <AuthProvider>
          <div className='flex'>
            <SideNav />
            <main className='flex-1'>
              <MarginWidthWrapper>
                <Header />
                <HeaderMobile />
                <PageWrapper>
                  {children}
                </PageWrapper>
              </MarginWidthWrapper>
              
            </main>
            
          </div> 
        </AuthProvider>
        <Toaster/>
        </body>
    </html>
  )
}
